# Generated by Django 3.2.7 on 2021-10-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120, unique=True)),
                ('mobile_model', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
